name: Rust

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust Version Info
      run: |
        cargo version
        rustc --version
        cargo clippy --version

    - name: Format
      run: cargo fmt --all -- --check

    - name: Check no-std
      run: cargo check --all-targets --no-default-features # still broken --locked

    - name: Build
      run: cargo build --all-targets --features derive_debug --locked

    - name: Test
      run: cargo test --locked --all-targets --features derive_debug

    - name: Clippy
      run: cargo clippy --locked --all-targets --features derive_debug -- -D warnings

    - name: Documentation
      run: cargo doc --locked --no-deps --features derive_debug

    - name: Doc Test
      run: cargo test --locked --doc
