[package]
name = "derive"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro-warning = { path = "../../proc-macro-warning" }
quote = "1.0.33"
syn = "2.0.42"
